# http://travis-ci.org/#!/facebook/tornado
language: python
python:
    - 2.6
    - 2.7
    - pypy
    - 3.2
    - 3.3
matrix:
    include:
        - python: 2.6
          env: MINIMAL="true"
        - python: 2.7
          env: MINIMAL="true"
        - python: pypy
          env: MINIMAL="true"
        - python: 3.2
          env: MINIMAL="true"
        - python: 3.3
          env: MINIMAL="true"
        - python: 2.7
          env: FLAGS="--httpclient=tornado.curl_httpclient.CurlAsyncHTTPClient"
        - python: 2.7
          env: FLAGS="--ioloop=tornado.platform.select.SelectIOLoop"
        - python: 2.7
          env: FLAGS="--ioloop=tornado.platform.twisted.TwistedIOLoop"
        - python: 2.7
          env: FLAGS="--resolver=tornado.netutil.ThreadedResolver"
        - python: 2.7
          env: FLAGS="--resolver=tornado.platform.twisted.TwistedResolver"
        - python: 2.7
          env: DEPS="pycares" FLAGS="--resolver=tornado.platform.caresresolver.CaresResolver"
        - python: 3.2
          env: DEPS="pycares" FLAGS="--resolver=tornado.platform.caresresolver.CaresResolver"
        - python: 2.7
          env: DEPS="http://pypi.python.org/packages/source/M/Monotime/Monotime-1.0.tar.gz" FLAGS="--ioloop_time_monotonic"
        - python: 3.3
          env: FLAGS="--ioloop_time_monotonic"
        - python: 2.7
          env: PYFLAGS="-O"
        - python: 3.2
          env: PYFLAGS="-O"
        - python: 3.2
          env: LANG="en_US.utf-8"
        - python: 3.2
          env: LANG="C"
        - python: 3.2
          env: PYFLAGS="-bb"
        - python: 3.3
          env: PYFLAGS="-bb"
install:
    # librtmp-dev is required to build libcurl
    - sudo apt-get install librtmp-dev
    # always install unittest2 on py26 even if $DEPS is unset
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' && -z "$MINIMAL" ]]; then pip install --use-mirrors futures mock pycurl twisted; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && -z "$MINIMAL" ]]; then pip install --use-mirrors futures mock pycurl twisted; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' && -z "$MINIMAL" ]]; then pip install --use-mirrors futures mock; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' && -z "$MINIMAL" ]]; then pip install --use-mirrors mock; fi
    - if [[ "$DEPS" ]]; then pip install --use-mirrors $DEPS; fi
    - python setup.py install
script:
    # Must cd somewhere else so python3 doesn't get confused and run
    # the python2 code from the current directory instead of the installed
    # 2to3 version.
    - cd maint
    - python $PYFLAGS -m tornado.test.runtests $FLAGS
